fruta = input("Escreva uma fruta:")
verdura = input("Escreva uma verdura:")
legume = input("Escreva um legume:")
print("Aqui estão os nomes de uma fruta, uma verdura e um legume")
print("A fruta é", fruta, "a verdura é", verdura, "já o legume é", legume)
